-- Migracao para habilitar o campo E-mail e o sistema de etiquetas (tags)
-- dos correspondentes. Execute UMA VEZ no Supabase:
--   painel do Supabase > SQL Editor > New query > cole este conteudo > Run

alter table advogados add column if not exists email text;
alter table advogados add column if not exists etiquetas text;

create table if not exists etiquetas_correspondentes (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  cor text
);

alter table etiquetas_correspondentes disable row level security;
